# Data Exploration

In [1]:
#import relevant Packages
import pandas as pd
import numpy as np
from sportsipy.mlb.boxscore import Boxscore
from sportsipy.mlb.boxscore import Boxscores

In [2]:
# Try calling in some games from Boxscores
game_data = Boxscore('BOS/BOS201808020')
print(game_data.home_runs)  # Prints 15
print(game_data.away_runs)  # Prints 7
df = game_data.dataframe
from datetime import datetime
from sportsipy.mlb.boxscore import Boxscores

games = Boxscores(datetime(2017, 7, 17), datetime(2017, 7, 17))

15
7

In [3]:
games_dict=games.games

In [4]:
#Examine raw games dictionary
games_dict

{'7-17-2017': [{'boxscore': 'BAL/BAL201707170',
   'away_name': 'Texas Rangers',
   'away_abbr': 'TEX',
   'away_score': 1,
   'home_name': 'Baltimore Orioles',
   'home_abbr': 'BAL',
   'home_score': 3,
   'winning_name': 'Baltimore Orioles',
   'winning_abbr': 'BAL',
   'losing_name': 'Texas Rangers',
   'losing_abbr': 'TEX'},
  {'boxscore': 'PIT/PIT201707170',
   'away_name': 'Milwaukee Brewers',
   'away_abbr': 'MIL',
   'away_score': 2,
   'home_name': 'Pittsburgh Pirates',
   'home_abbr': 'PIT',
   'home_score': 4,
   'winning_name': 'Pittsburgh Pirates',
   'winning_abbr': 'PIT',
   'losing_name': 'Milwaukee Brewers',
   'losing_abbr': 'MIL'},
  {'boxscore': 'BOS/BOS201707170',
   'away_name': 'Toronto Blue Jays',
   'away_abbr': 'TOR',
   'away_score': 4,
   'home_name': 'Boston Red Sox',
   'home_abbr': 'BOS',
   'home_score': 3,
   'winning_name': 'Toronto Blue Jays',
   'winning_abbr': 'TOR',
   'losing_name': 'Boston Red Sox',
   'losing_abbr': 'BOS'},
  {'boxscore': 'MIA/MIA201707170',
   'away_name': 'Philadelphia Phillies',
   'away_abbr': 'PHI',
   'away_score': 5,
   'home_name': 'Miami Marlins',
   'home_abbr': 'MIA',
   'home_score': 6,
   'winning_name': 'Miami Marlins',
   'winning_abbr': 'MIA',
   'losing_name': 'Philadelphia Phillies',
   'losing_abbr': 'PHI'},
  {'boxscore': 'NYN/NYN201707170',
   'away_name': 'St. Louis Cardinals',
   'away_abbr': 'STL',
   'away_score': 6,
   'home_name': 'New York Mets',
   'home_abbr': 'NYM',
   'home_score': 3,
   'winning_name': 'St. Louis Cardinals',
   'winning_abbr': 'STL',
   'losing_name': 'New York Mets',
   'losing_abbr': 'NYM'},
  {'boxscore': 'ATL/ATL201707170',
   'away_name': 'Chicago Cubs',
   'away_abbr': 'CHC',
   'away_score': 4,
   'home_name': 'Atlanta Braves',
   'home_abbr': 'ATL',
   'home_score': 3,
   'winning_name': 'Chicago Cubs',
   'winning_abbr': 'CHC',
   'losing_name': 'Atlanta Braves',
   'losing_abbr': 'ATL'},
  {'boxscore': 'HOU/HOU201707170',
   'away_name': 'Seattle Mariners',
   'away_abbr': 'SEA',
   'away_score': 9,
   'home_name': 'Houston Astros',
   'home_abbr': 'HOU',
   'home_score': 7,
   'winning_name': 'Seattle Mariners',
   'winning_abbr': 'SEA',
   'losing_name': 'Houston Astros',
   'losing_abbr': 'HOU'},
  {'boxscore': 'MIN/MIN201707170',
   'away_name': 'New York Yankees',
   'away_abbr': 'NYY',
   'away_score': 2,
   'home_name': 'Minnesota Twins',
   'home_abbr': 'MIN',
   'home_score': 4,
   'winning_name': 'Minnesota Twins',
   'winning_abbr': 'MIN',
   'losing_name': 'New York Yankees',
   'losing_abbr': 'NYY'},
  {'boxscore': 'KCA/KCA201707170',
   'away_name': 'Detroit Tigers',
   'away_abbr': 'DET',
   'away_score': 10,
   'home_name': 'Kansas City Royals',
   'home_abbr': 'KCR',
   'home_score': 2,
   'winning_name': 'Detroit Tigers',
   'winning_abbr': 'DET',
   'losing_name': 'Kansas City Royals',
   'losing_abbr': 'KCR'},
  {'boxscore': 'COL/COL201707170',
   'away_name': 'San Diego Padres',
   'away_abbr': 'SDP',
   'away_score': 6,
   'home_name': 'Colorado Rockies',
   'home_abbr': 'COL',
   'home_score': 9,
   'winning_name': 'Colorado Rockies',
   'winning_abbr': 'COL',
   'losing_name': 'San Diego Padres',
   'losing_abbr': 'SDP'},
  {'boxscore': 'OAK/OAK201707170',
   'away_name': 'Tampa Bay Rays',
   'away_abbr': 'TBR',
   'away_score': 3,
   'home_name': 'Oakland Athletics',
   'home_abbr': 'OAK',
   'home_score': 2,
   'winning_name': 'Tampa Bay Rays',
   'winning_abbr': 'TBR',
   'losing_name': 'Oakland Athletics',
   'losing_abbr': 'OAK'},
  {'boxscore': 'SFN/SFN201707170',
   'away_name': 'Cleveland Indians',
   'away_abbr': 'CLE',
   'away_score': 5,
   'home_name': 'San Francisco Giants',
   'home_abbr': 'SFG',
   'home_score': 3,
   'winning_name': 'Cleveland Indians',
   'winning_abbr': 'CLE',
   'losing_name': 'San Francisco Giants',
   'losing_abbr': 'SFG'},
  {'boxscore': 'CIN/CIN201707170',
   'away_name': 'Washington Nationals',
   'away_abbr': 'WSN',
   'away_score': 6,
   'home_name': 'Cincinnati Reds',
   'home_abbr': 'CIN',
   'home_score': 1,
   'winning_name': 'Washington Nationals',
   'winning_abbr': 'WSN',
   'losing_name': 'Cincinnati Reds',
   'losing_abbr': 'CIN'}]}

In [5]:
# Function to return games in certain time range
def get_current_games(date,end_date,end_week=None):
    
    games = Boxscores(date,end_date)
    schedule = games.games

    game_days = []
    for day in schedule.values():
        for game in day:
            game_days.append(game['boxscore'])
            
    season_games = []

    for i in game_days:
        temp = Boxscore(i).dataframe
        season_games.append(temp)

    df = pd.concat(season_games, axis = 0).reset_index()

    return df

In [7]:
seasons19=get_current_games(datetime(2019, 3, 28),datetime(2019, 9, 29))

In [8]:
seasons19.head()

,index,date,time,venue,attendance,duration,time_of_day,winner,winning_name,winning_abbr,...,home_strikes_looking,home_grounded_balls,home_fly_balls,home_line_drives,home_unknown_bat_type,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved
0,NYA/NYA201903280,"Thursday, March 28, 2019",1:12 p.m. Local,Yankee Stadium III,46928,3:06,Day,Home,New York Yankees,NYY,...,35,9,13,4,0,56,1,0,0.240,2.9
1,WAS/WAS201903280,"Thursday, March 28, 2019",1:07 p.m. Local,Nationals Park,42263,2:44,Day,Away,New York Mets,NYM,...,24,5,12,8,0,76,3,1,0.226,3.1
2,MIL/MIL201903280,"Thursday, March 28, 2019",1:10 p.m. Local,Miller Park,45304,2:36,Day,Home,Milwaukee Brewers,MIL,...,28,14,11,3,0,55,1,0,0.321,0.8
3,PHI/PHI201903280,"Thursday, March 28, 2019",3:08 p.m. Local,Citizens Bank Park,44469,3:04,Day,Home,Philadelphia Phillies,PHI,...,22,13,9,0,0,67,0,0,0.230,0.9
4,TOR/TOR201903280,"Thursday, March 28, 2019",4:08 p.m. Local,Rogers Centre,45048,2:25,Day,Away,Detroit Tigers,DET,...,16,9,16,5,0,76,0,0,0.310,3.4

In [9]:
seasons19.to_csv('../data/reg_season19_raw.csv')

In [10]:
df=pd.read_csv('../data/reg_season19_raw.csv')

# Data Exploration

In [11]:
#Examine where we are at to begin with
df.head()

,Unnamed: 0,index,date,time,venue,attendance,duration,time_of_day,winner,winning_name,...,home_strikes_looking,home_grounded_balls,home_fly_balls,home_line_drives,home_unknown_bat_type,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved
0,0,NYA/NYA201903280,"Thursday, March 28, 2019",1:12 p.m. Local,Yankee Stadium III,46928.0,3:06,Day,Home,New York Yankees,...,35,9,13,4,0,56,1.0,0.0,0.240,2.9
1,1,WAS/WAS201903280,"Thursday, March 28, 2019",1:07 p.m. Local,Nationals Park,42263.0,2:44,Day,Away,New York Mets,...,24,5,12,8,0,76,3.0,1.0,0.226,3.1
2,2,MIL/MIL201903280,"Thursday, March 28, 2019",1:10 p.m. Local,Miller Park,45304.0,2:36,Day,Home,Milwaukee Brewers,...,28,14,11,3,0,55,1.0,0.0,0.321,0.8
3,3,PHI/PHI201903280,"Thursday, March 28, 2019",3:08 p.m. Local,Citizens Bank Park,44469.0,3:04,Day,Home,Philadelphia Phillies,...,22,13,9,0,0,67,0.0,0.0,0.230,0.9
4,4,TOR/TOR201903280,"Thursday, March 28, 2019",4:08 p.m. Local,Rogers Centre,45048.0,2:25,Day,Away,Detroit Tigers,...,16,9,16,5,0,76,0.0,0.0,0.310,3.4

In [12]:
df.columns

Index(['Unnamed: 0', 'index', 'date', 'time', 'venue', 'attendance',
       'duration', 'time_of_day', 'winner', 'winning_name', 'winning_abbr',
       'losing_name', 'losing_abbr', 'away_at_bats', 'away_runs', 'away_hits',
       'away_rbi', 'away_earned_runs', 'away_bases_on_balls',
       'away_strikeouts', 'away_plate_appearances', 'away_batting_average',
       'away_on_base_percentage', 'away_slugging_percentage',
       'away_on_base_plus', 'away_pitches', 'away_strikes',
       'away_win_probability_for_offensive_player',
       'away_average_leverage_index', 'away_win_probability_added',
       'away_win_probability_subtracted', 'away_base_out_runs_added',
       'away_putouts', 'away_assists', 'away_innings_pitched',
       'away_home_runs', 'away_strikes_by_contact', 'away_strikes_swinging',
       'away_strikes_looking', 'away_grounded_balls', 'away_fly_balls',
       'away_line_drives', 'away_unknown_bat_type', 'away_game_score',
       'away_inherited_runners', 'away_inherited_score',
       'away_win_probability_by_pitcher', 'away_base_out_runs_saved',
       'home_at_bats', 'home_runs', 'home_hits', 'home_rbi',
       'home_earned_runs', 'home_bases_on_balls', 'home_strikeouts',
       'home_plate_appearances', 'home_batting_average',
       'home_on_base_percentage', 'home_slugging_percentage',
       'home_on_base_plus', 'home_pitches', 'home_strikes',
       'home_win_probability_for_offensive_player',
       'home_average_leverage_index', 'home_win_probability_added',
       'home_win_probability_subtracted', 'home_base_out_runs_added',
       'home_putouts', 'home_assists', 'home_innings_pitched',
       'home_home_runs', 'home_strikes_by_contact', 'home_strikes_swinging',
       'home_strikes_looking', 'home_grounded_balls', 'home_fly_balls',
       'home_line_drives', 'home_unknown_bat_type', 'home_game_score',
       'home_inherited_runners', 'home_inherited_score',
       'home_win_probability_by_pitcher', 'home_base_out_runs_saved'],
      dtype='object')

In [13]:
df.head()

,Unnamed: 0,index,date,time,venue,attendance,duration,time_of_day,winner,winning_name,...,home_strikes_looking,home_grounded_balls,home_fly_balls,home_line_drives,home_unknown_bat_type,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved
0,0,NYA/NYA201903280,"Thursday, March 28, 2019",1:12 p.m. Local,Yankee Stadium III,46928.0,3:06,Day,Home,New York Yankees,...,35,9,13,4,0,56,1.0,0.0,0.240,2.9
1,1,WAS/WAS201903280,"Thursday, March 28, 2019",1:07 p.m. Local,Nationals Park,42263.0,2:44,Day,Away,New York Mets,...,24,5,12,8,0,76,3.0,1.0,0.226,3.1
2,2,MIL/MIL201903280,"Thursday, March 28, 2019",1:10 p.m. Local,Miller Park,45304.0,2:36,Day,Home,Milwaukee Brewers,...,28,14,11,3,0,55,1.0,0.0,0.321,0.8
3,3,PHI/PHI201903280,"Thursday, March 28, 2019",3:08 p.m. Local,Citizens Bank Park,44469.0,3:04,Day,Home,Philadelphia Phillies,...,22,13,9,0,0,67,0.0,0.0,0.230,0.9
4,4,TOR/TOR201903280,"Thursday, March 28, 2019",4:08 p.m. Local,Rogers Centre,45048.0,2:25,Day,Away,Detroit Tigers,...,16,9,16,5,0,76,0.0,0.0,0.310,3.4

In [14]:
#set date to datetime
df.date=pd.to_datetime(df.date)

In [15]:
#Set date as index
df.set_index(df.date,inplace=True)

In [16]:
#Get rid of whitespace
for column in df.columns:
    column.strip()

In [17]:
#drop no longer needed columns
df.drop(['Unnamed: 0','index'],axis=1,inplace=True)

In [18]:
#drop date column as it is now in index
df.drop(['date'],axis=1,inplace=True)

In [19]:
df.head()

,time,venue,attendance,duration,time_of_day,winner,winning_name,winning_abbr,losing_name,losing_abbr,...,home_strikes_looking,home_grounded_balls,home_fly_balls,home_line_drives,home_unknown_bat_type,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved
date,,,,,,,,,,,,,,,,,,,,,
2019-03-28,1:12 p.m. Local,Yankee Stadium III,46928.0,3:06,Day,Home,New York Yankees,NYY,Baltimore Orioles,BAL,...,35,9,13,4,0,56,1.0,0.0,0.240,2.9
2019-03-28,1:07 p.m. Local,Nationals Park,42263.0,2:44,Day,Away,New York Mets,NYM,Washington Nationals,WSN,...,24,5,12,8,0,76,3.0,1.0,0.226,3.1
2019-03-28,1:10 p.m. Local,Miller Park,45304.0,2:36,Day,Home,Milwaukee Brewers,MIL,St. Louis Cardinals,STL,...,28,14,11,3,0,55,1.0,0.0,0.321,0.8
2019-03-28,3:08 p.m. Local,Citizens Bank Park,44469.0,3:04,Day,Home,Philadelphia Phillies,PHI,Atlanta Braves,ATL,...,22,13,9,0,0,67,0.0,0.0,0.230,0.9
2019-03-28,4:08 p.m. Local,Rogers Centre,45048.0,2:25,Day,Away,Detroit Tigers,DET,Toronto Blue Jays,TOR,...,16,9,16,5,0,76,0.0,0.0,0.310,3.4

In [20]:
#Limit data to 2019 MLB Season
df_19=df

In [21]:
#Put home and away winners in own dataframes
Home = df_19[(df_19['winner'] == 'Home')] 
Away= df_19[(df_19['winner'] == 'Away')]

In [22]:
#yankees home and away wins in own df as example of what will be done to every team
yankees_home_wins=Home[(Home['winning_abbr'] == 'NYY')]
yankees_away_wins=Away[(Away['winning_abbr']=='NYY')]

In [23]:
#yanks total wins concated together
yankees_wins=pd.concat([yankees_home_wins,yankees_away_wins])

In [24]:
#84 wins
yankees_wins.winning_abbr.value_counts()

NYY    103
Name: winning_abbr, dtype: int64

In [25]:
#Yanks home and away losses
yankees_home_loss=Home[(Home['losing_abbr'] == 'NYY')]
yankees_away_loss=Away[(Away['losing_abbr']=='NYY')]

In [26]:
#combine dataframes of yanks losses
yankees_loss=pd.concat([yankees_home_loss,yankees_away_loss])

In [27]:
#78 losses 
yankees_loss.losing_abbr.value_counts()

NYY    59
Name: losing_abbr, dtype: int64

In [28]:
#combine to make complete 2018 season
yankees_16=pd.concat([yankees_wins,yankees_loss])

In [29]:
yankees_16.head()

,time,venue,attendance,duration,time_of_day,winner,winning_name,winning_abbr,losing_name,losing_abbr,...,home_strikes_looking,home_grounded_balls,home_fly_balls,home_line_drives,home_unknown_bat_type,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved
date,,,,,,,,,,,,,,,,,,,,,
2019-03-28,1:12 p.m. Local,Yankee Stadium III,46928.0,3:06,Day,Home,New York Yankees,NYY,Baltimore Orioles,BAL,...,35,9,13,4,0,56,1.0,0.0,0.240,2.9
2019-04-01,6:39 p.m. Local,Yankee Stadium III,32036.0,2:43,Night,Home,New York Yankees,NYY,Detroit Tigers,DET,...,26,12,9,3,0,65,0.0,0.0,0.496,3.9
2019-04-13,1:08 p.m. Local,Yankee Stadium III,41176.0,2:28,Day,Home,New York Yankees,NYY,Chicago White Sox,CHW,...,18,12,12,8,0,68,0.0,0.0,0.521,4.9
2019-04-16,6:39 p.m. Local,Yankee Stadium III,45008.0,2:23,Night,Home,New York Yankees,NYY,Boston Red Sox,BOS,...,20,13,15,7,0,89,0.0,0.0,0.298,4.9
2019-04-17,6:38 p.m. Local,Yankee Stadium III,44106.0,2:56,Night,Home,New York Yankees,NYY,Boston Red Sox,BOS,...,28,10,10,4,0,52,1.0,0.0,0.159,1.9

### Team Reg Season Function walkthrough outside to find potential bugs

In [30]:
#Rename columns to avoid deletetion later
df_19=df_19.rename(columns={'home_home_runs':'home_HR','away_home_runs':'away_HR'})

In [31]:
df_19.columns

Index(['time', 'venue', 'attendance', 'duration', 'time_of_day', 'winner',
       'winning_name', 'winning_abbr', 'losing_name', 'losing_abbr',
       'away_at_bats', 'away_runs', 'away_hits', 'away_rbi',
       'away_earned_runs', 'away_bases_on_balls', 'away_strikeouts',
       'away_plate_appearances', 'away_batting_average',
       'away_on_base_percentage', 'away_slugging_percentage',
       'away_on_base_plus', 'away_pitches', 'away_strikes',
       'away_win_probability_for_offensive_player',
       'away_average_leverage_index', 'away_win_probability_added',
       'away_win_probability_subtracted', 'away_base_out_runs_added',
       'away_putouts', 'away_assists', 'away_innings_pitched', 'away_HR',
       'away_strikes_by_contact', 'away_strikes_swinging',
       'away_strikes_looking', 'away_grounded_balls', 'away_fly_balls',
       'away_line_drives', 'away_unknown_bat_type', 'away_game_score',
       'away_inherited_runners', 'away_inherited_score',
       'away_win_probability_by_pitcher', 'away_base_out_runs_saved',
       'home_at_bats', 'home_runs', 'home_hits', 'home_rbi',
       'home_earned_runs', 'home_bases_on_balls', 'home_strikeouts',
       'home_plate_appearances', 'home_batting_average',
       'home_on_base_percentage', 'home_slugging_percentage',
       'home_on_base_plus', 'home_pitches', 'home_strikes',
       'home_win_probability_for_offensive_player',
       'home_average_leverage_index', 'home_win_probability_added',
       'home_win_probability_subtracted', 'home_base_out_runs_added',
       'home_putouts', 'home_assists', 'home_innings_pitched', 'home_HR',
       'home_strikes_by_contact', 'home_strikes_swinging',
       'home_strikes_looking', 'home_grounded_balls', 'home_fly_balls',
       'home_line_drives', 'home_unknown_bat_type', 'home_game_score',
       'home_inherited_runners', 'home_inherited_score',
       'home_win_probability_by_pitcher', 'home_base_out_runs_saved'],
      dtype='object')

In [32]:
#Isolate Home winners and away winners into their own df
Home = df_19[(df_19['winner'] == 'Home')] 
Away= df_19[(df_19['winner'] == 'Away')]

In [33]:
#Yanks home wins and losses isolated then combined to only have their stats from those games
home_wins=Home[(Home['winning_abbr'] == 'NYY')]
home_loss=Away[(Away['losing_abbr'] == 'NYY')]
home_games= pd.concat([home_wins,home_loss])
home_offense = home_games.filter(like = 'home')

In [34]:
#Yanks away wins and losses isolated then combined to only have their stats from those games
away_wins=Away[(Away['winning_abbr']=='NYY')]
away_loss=Home[(Home['losing_abbr']=='NYY')]
away_games= pd.concat([away_wins,away_loss])
away_offense = away_games.filter(like = 'away')

In [35]:
#Get rid of the words home/away
home_offense.columns = home_offense.columns.str.replace('home_','')
away_offense.columns = away_offense.columns.str.replace('away_','')

In [36]:
#home_offense.drop('away_runs',axis=1,inplace=True)

In [37]:
#Check to make sure that the columns are the same for both data frames
home_offense.columns==away_offense.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [38]:
#Combine dataframes to make one dataframe of all this teams stats
team_offense = pd.concat([home_offense, away_offense])

In [39]:
#From the teams given home games take the stats of the team they played against
home_games_opponents = home_games.filter(like = 'away')
away_games_opponents = away_games.filter(like = 'home')

In [40]:
#Get rid of the words home/away
home_games_opponents.columns = home_games_opponents.columns.str.replace('away_','')
away_games_opponents.columns = away_games_opponents.columns.str.replace('home_','')

In [41]:
#Combine to make dataframe of stats from all opponents 
team_opponents= pd.concat([home_games_opponents,away_games_opponents])

In [42]:
#Combine theirs and the opponents to make one full data frame for the team, put an Opp_ 
#prefix in front of opponent stats
team_full_check = pd.concat([team_offense, team_opponents.add_prefix('Opp_')], axis = 1)

In [43]:
team_full_check.head()

,at_bats,runs,hits,rbi,earned_runs,bases_on_balls,strikeouts,plate_appearances,batting_average,on_base_percentage,...,Opp_strikes_looking,Opp_grounded_balls,Opp_fly_balls,Opp_line_drives,Opp_unknown_bat_type,Opp_game_score,Opp_inherited_runners,Opp_inherited_score,Opp_win_probability_by_pitcher,Opp_base_out_runs_saved
date,,,,,,,,,,,,,,,,,,,,,
2019-03-28,29,7,9,6,7.88,8,8,39,0.310,0.462,...,27,15,10,5,0,25,2.0,2.0,-0.260,-2.7
2019-04-01,29,3,5,2,2.25,4,8,33,0.172,0.273,...,23,6,14,4,0,49,0.0,0.0,-0.006,1.3
2019-04-13,29,4,7,4,2.25,1,7,32,0.241,0.258,...,25,12,8,2,0,64,3.0,2.0,0.021,0.3
2019-04-16,34,8,11,8,9.00,2,7,38,0.324,0.378,...,23,6,12,5,0,42,0.0,0.0,-0.203,-3.7
2019-04-17,30,5,5,5,4.50,3,10,33,0.167,0.242,...,19,12,15,4,0,69,3.0,3.0,-0.342,-0.7

I need to create a column that has the teams name in it all the way down, below I will try and make this column using the LAD as my example

In [60]:
#assumed 162 games played
#LAD=(('LAD',)*162)

In [61]:
# d = {'TEAM':LAD}
# ser = pd.Series(data=d, index=['TEAM'])

In [62]:
#create name column and fill it with the new LAD variable made above
#team_full_check['name']= LAD

In [44]:
team_full_check = team_full_check.assign(name='LAD')

In [45]:
team_full_check = team_full_check.groupby('name').mean().reset_index()

In [46]:
team_full_check

,name,at_bats,runs,hits,rbi,earned_runs,bases_on_balls,strikeouts,plate_appearances,batting_average,...,Opp_strikes_looking,Opp_grounded_balls,Opp_fly_balls,Opp_line_drives,Opp_unknown_bat_type,Opp_game_score,Opp_inherited_runners,Opp_inherited_score,Opp_win_probability_by_pitcher,Opp_base_out_runs_saved
0,LAD,34.462963,5.820988,9.216049,5.580247,5.632593,3.512346,8.87037,38.549383,0.262302,...,24.709877,10.765432,14.197531,6.012346,0.0,46.407407,1.641975,0.580247,-0.084432,-1.07963

### Build reusable Function

In [47]:
def team_regular_season(df,team,average=True,num=162):
    #Set year range for what games you want to access
    #Rename columns to avoid deletetion later
    df=df.rename(columns={'home_home_runs':'home_HR','away_home_runs':'away_HR'})
    
        #Get all the home winner and away winner games alone
    Home = df[(df['winner'] == 'Home')] 
    Away= df[(df['winner'] == 'Away')]
    
        #Get games where the team was the home team
    home_wins=Home[(Home['winning_abbr'] == team)]
    home_loss=Away[(Away['losing_abbr'] == team)]
    home_games= pd.concat([home_wins,home_loss])
    home_offense = home_games.filter(like = 'home')
    
      #Get games where the team was the away team
    away_wins=Away[(Away['winning_abbr']==team)]
    away_loss=Home[(Home['losing_abbr']==team)]
    away_games= pd.concat([away_wins,away_loss])
    away_offense = away_games.filter(like = 'away')
    
        # split the dataframes to only have the statistics of the given team
    home_offense.columns = home_offense.columns.str.replace('home_','')
    away_offense.columns = away_offense.columns.str.replace('away_','')
    
    #combine offensive stats into one df
    team_offense = pd.concat([home_offense, away_offense])
    
        # create oppposing team statistics from the given games
    home_games_opponents = home_games.filter(like = 'away')
    away_games_opponents = away_games.filter(like = 'home')
    
        # rename the columns from the opponent statistics dataframes
    home_games_opponents.columns = home_games_opponents.columns.str.replace('away_','')
    away_games_opponents.columns = away_games_opponents.columns.str.replace('home_','')
    
    team_opponents= pd.concat([home_games_opponents,away_games_opponents])
    
        # concat the team stats and the opponent stats to create a full picture of the team's season
    team_full = pd.concat([team_offense, team_opponents.add_prefix('Opp_')], axis = 1)
    team_full = team_full.assign(name=team)
    
    # Certain teams only played 161 games this season and therefor need different number
#     club_161=['DET','CLE','MIA','ATL']
#     if team in club_161:
#         num=161
#     else:
#         num=162
#     add= ((team,)*num)
#     team_full['name']= add
    
    
        # return either the season averages or the game by game statistics
    if average:
            team_full = team_full.groupby('name').mean().reset_index()
    
    
    return team_full

In [48]:
#Check unique names
df.winning_abbr.unique()

array(['NYY', 'NYM', 'MIL', 'PHI', 'DET', 'HOU', 'CHC', 'OAK', 'CIN',
       'LAD', 'COL', 'MIN', 'SDP', 'KCR', 'SEA', 'TOR', 'TBR', 'STL',
       'LAA', 'ARI', 'BOS', 'BAL', 'CLE', 'MIA', 'TEX', 'SFG', 'PIT',
       'WSN', 'CHW', 'ATL'], dtype=object)

In [49]:
#Below examined that each teams abbr was working in the function including the 161 teams
dodgers_19=team_regular_season(df,'LAD')

In [50]:
dodgers_19

,name,at_bats,runs,hits,rbi,earned_runs,bases_on_balls,strikeouts,plate_appearances,batting_average,...,Opp_strikes_looking,Opp_grounded_balls,Opp_fly_balls,Opp_line_drives,Opp_unknown_bat_type,Opp_game_score,Opp_inherited_runners,Opp_inherited_score,Opp_win_probability_by_pitcher,Opp_base_out_runs_saved
0,LAD,33.907407,5.469136,8.728395,5.314815,5.250432,3.746914,8.37037,38.777778,0.252296,...,23.833333,11.265432,13.018519,5.858025,0.0,48.216049,1.481481,0.45679,-0.074901,-0.858642

### Single Game Function Walkthrough to find/fix bugs

In [51]:
#create regular seasons using yankees and mets as our example
yanks_19=team_regular_season(df,'NYY')
mets_19=team_regular_season(df,'NYM')

In [52]:
#Concat them as if they are playing against one another 
pd.concat([yanks_19, mets_19])

,name,at_bats,runs,hits,rbi,earned_runs,bases_on_balls,strikeouts,plate_appearances,batting_average,...,Opp_strikes_looking,Opp_grounded_balls,Opp_fly_balls,Opp_line_drives,Opp_unknown_bat_type,Opp_game_score,Opp_inherited_runners,Opp_inherited_score,Opp_win_probability_by_pitcher,Opp_base_out_runs_saved
0,NYY,34.462963,5.820988,9.216049,5.580247,5.632593,3.512346,8.87037,38.549383,0.262302,...,24.709877,10.765432,14.197531,6.012346,0.000000,46.407407,1.641975,0.580247,-0.084432,-1.079630
0,NYM,34.716049,4.882716,8.919753,4.734568,4.590926,3.185185,8.54321,38.827160,0.252296,...,24.777778,11.364198,14.253086,6.351852,0.006173,50.135802,1.577640,0.534161,-0.024111,-0.288889

In [53]:
#Try this as we may prefer it to all be in one row
pd.concat([yanks_19.add_prefix('H_'), mets_19.add_prefix('A_')], axis = 1)

,H_name,H_at_bats,H_runs,H_hits,H_rbi,H_earned_runs,H_bases_on_balls,H_strikeouts,H_plate_appearances,H_batting_average,...,A_Opp_strikes_looking,A_Opp_grounded_balls,A_Opp_fly_balls,A_Opp_line_drives,A_Opp_unknown_bat_type,A_Opp_game_score,A_Opp_inherited_runners,A_Opp_inherited_score,A_Opp_win_probability_by_pitcher,A_Opp_base_out_runs_saved
0,NYY,34.462963,5.820988,9.216049,5.580247,5.632593,3.512346,8.87037,38.549383,0.262302,...,24.777778,11.364198,14.253086,6.351852,0.006173,50.135802,1.57764,0.534161,-0.024111,-0.288889

### Build Reusable Function

In [54]:
def single_game(team1_name, team2_name,df=df):
    
    # from the Team abbreviations get a dataframe with the average seasonlong team statistics.
    team1 = team_regular_season(df,team1_name)
    team2 = team_regular_season(df,team2_name)
    
    #make the single game by concating those dataframes
    game = pd.concat([team1.add_prefix('H_'), team2.add_prefix('A_')], axis = 1)
    
    return game

In [55]:
#test it using subway series again
subway=single_game('NYY','NYM',df)
subway

,H_name,H_at_bats,H_runs,H_hits,H_rbi,H_earned_runs,H_bases_on_balls,H_strikeouts,H_plate_appearances,H_batting_average,...,A_Opp_strikes_looking,A_Opp_grounded_balls,A_Opp_fly_balls,A_Opp_line_drives,A_Opp_unknown_bat_type,A_Opp_game_score,A_Opp_inherited_runners,A_Opp_inherited_score,A_Opp_win_probability_by_pitcher,A_Opp_base_out_runs_saved
0,NYY,34.462963,5.820988,9.216049,5.580247,5.632593,3.512346,8.87037,38.549383,0.262302,...,24.777778,11.364198,14.253086,6.351852,0.006173,50.135802,1.57764,0.534161,-0.024111,-0.288889

###  Create Season Function Walkthrough to Find Bugs

In [128]:
#df_16.drop(['index','level_0'],axis=1,inplace=True)

In [56]:
#Reset the index
df_19.reset_index(inplace=True)

In the cells below I will try and alter the dataframes so rather than tellin us the winning and losing name it will return the names of the home or away team

In [57]:
#Get home winners and Away winners in their own dataframe
Home = df_19[(df_19['winner'] == 'Home')] 
Away= df_19[(df_19['winner'] == 'Away')]

In [58]:
#Rename columns in the home win from winner and loser to home and away
Home=Home.rename(columns={'winning_abbr':'home_abbr','winning_name':'home_name','losing_name':'away_name',
                         'losing_abbr':'away_abbr'})

In [59]:
#Rename columns in the away win from winner and loser to home and away
Away= Away.rename(columns={'winning_abbr':'away_abbr','winning_name':'away_name','losing_name':'home_name',
                         'losing_abbr':'home_abbr'})

In [60]:
#Concat these to make season_df now the same but with these new column names
df_19= pd.concat([Home,Away])

In [61]:
#Get Home and away alone once again
Home = df_19[(df_19['winner'] == 'Home')] 
Away= df_19[(df_19['winner'] == 'Away')]

In [62]:
#Create a winning abbreviation column
Home['winning_abbr']= Home['home_abbr']
Away['winning_abbr']= Away['away_abbr']

<ipython-input-62-12da05963abd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Home['winning_abbr']= Home['home_abbr']
<ipython-input-62-12da05963abd>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Away['winning_abbr']= Away['away_abbr']

In [63]:
#Concat to update season_df
df_19=pd.concat([Home,Away])

In [64]:
#make it sorted in order of date
df_19=df_19.sort_values('date')

In [65]:
df_19.head()

,date,time,venue,attendance,duration,time_of_day,winner,home_name,home_abbr,away_name,...,home_grounded_balls,home_fly_balls,home_line_drives,home_unknown_bat_type,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved,winning_abbr
0,2019-03-28,1:12 p.m. Local,Yankee Stadium III,46928.0,3:06,Day,Home,New York Yankees,NYY,Baltimore Orioles,...,9,13,4,0,56,1.0,0.0,0.240,2.9,NYY
5,2019-03-28,4:00 p.m. Local,Tropicana Field,25025.0,2:38,Day,Away,Tampa Bay Rays,TBR,Houston Astros,...,10,9,5,0,41,0.0,0.0,-0.222,-0.2,HOU
6,2019-03-28,3:08 p.m. Local,Globe Life Park in Arlington,48538.0,3:07,Day,Away,Texas Rangers,TEX,Chicago Cubs,...,9,17,8,0,31,10.0,4.0,-0.431,-6.5,CHC
10,2019-03-28,4:12 p.m. Local,Marlins Park,25423.0,2:55,Day,Away,Miami Marlins,MIA,Colorado Rockies,...,14,11,3,0,25,1.0,0.0,-0.246,-1.5,COL
4,2019-03-28,4:08 p.m. Local,Rogers Centre,45048.0,2:25,Day,Away,Toronto Blue Jays,TOR,Detroit Tigers,...,9,16,5,0,76,0.0,0.0,0.310,3.4,DET

In [66]:
# create a list with the two teams, home team always first, the season, and the day number of the game
matchups = list(zip(df_19.home_abbr, df_19.away_abbr, df_19.date, df_19.winning_abbr))

In [67]:
#Check matchups
matchups[-2]

('SFG', 'LAD', Timestamp('2019-09-29 00:00:00'), 'LAD')

In [68]:
#empty season_games list
season_games = []

In [69]:
#loop through matchups and create single games for each matchup using that function, then append to season games
for team in matchups:
        game = single_game(team[0], team[1],df)
        season_games.append(game)

In [70]:
#create df_prep as a example for what will hopefully happen in a function
df_prep = pd.concat(season_games, axis = 0)

In [71]:
#reset_index
df_prep.reset_index(inplace = True, drop = True)

In [72]:
df_prep

,H_name,H_at_bats,H_runs,H_hits,H_rbi,H_earned_runs,H_bases_on_balls,H_strikeouts,H_plate_appearances,H_batting_average,...,A_Opp_strikes_looking,A_Opp_grounded_balls,A_Opp_fly_balls,A_Opp_line_drives,A_Opp_unknown_bat_type,A_Opp_game_score,A_Opp_inherited_runners,A_Opp_inherited_score,A_Opp_win_probability_by_pitcher,A_Opp_base_out_runs_saved
0,NYY,34.462963,5.820988,9.216049,5.580247,5.632593,3.512346,8.870370,38.549383,0.262302,...,24.191358,11.413580,16.395062,7.179012,0.000000,50.549383,1.385093,0.347826,0.068586,0.470370
1,TBR,34.740741,4.746914,8.808642,4.506173,4.573704,3.345679,9.216049,38.796296,0.249895,...,25.209877,10.450617,13.179012,5.604938,0.018519,44.759259,1.679245,0.515723,-0.041290,-0.733333
2,TEX,34.197531,5.000000,8.481481,4.722222,4.666852,3.296296,9.740741,38.296296,0.242006,...,25.666667,11.913580,13.555556,6.617284,0.000000,48.759259,1.487654,0.462963,-0.006420,-0.281481
3,MIA,34.024691,3.796296,8.185185,3.660494,3.545988,2.438272,9.067901,37.314815,0.234074,...,23.919753,13.172840,14.685185,7.179012,0.000000,48.524691,1.347826,0.453416,0.017148,-0.015432
4,TOR,33.907407,4.481481,8.018519,4.302469,4.286975,3.141975,9.345679,37.598765,0.229025,...,25.329193,11.869565,15.248447,6.645963,0.006211,54.776398,1.139241,0.316456,0.134677,1.446584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2422,COL,34.938272,5.154321,9.271605,4.956790,4.874444,3.018519,9.277778,38.814815,0.260759,...,24.716049,11.104938,14.345679,6.413580,0.000000,51.012346,1.530864,0.444444,-0.006605,0.037037
2423,NYM,34.716049,4.882716,8.919753,4.734568,4.590926,3.185185,8.543210,38.827160,0.252296,...,24.253086,12.148148,13.956790,6.567901,0.006173,50.203704,1.416149,0.484472,-0.045481,-0.516667
2424,SEA,33.912500,4.650000,8.056250,4.475000,4.434688,3.606250,9.762500,38.168750,0.231038,...,24.243750,11.356250,15.212500,6.450000,0.000000,49.300000,1.440252,0.427673,-0.045588,-0.432500
2425,SFG,34.438272,4.185185,8.222222,4.043210,3.882099,2.932099,8.858025,38.086420,0.233296,...,23.833333,11.265432,13.018519,5.858025,0.000000,48.216049,1.481481,0.456790,-0.074901,-0.858642
2426,LAA,34.209877,4.746914,8.444444,4.530864,4.473765,3.617284,7.876543,38.586420,0.241494,...,25.209877,10.450617,13.179012,5.604938,0.018519,44.759259,1.679245,0.515723,-0.041290,-0.733333

In [74]:
#df_prep.drop(['H_median_odds','A_median_odds'],axis=1,inplace=True)

In [75]:
#Create new column where it will have a 1 if home team won and 0 if away team won
df_prep['home_win'] = np.where(df_19.home_abbr ==df_19.winning_abbr,
                  [1],
                  [0])

In [163]:
#season_df['home_win'] = np.where(season_df.home_name == season_df.winning_abbr,1,0)

In [76]:
df_prep

,H_name,H_at_bats,H_runs,H_hits,H_rbi,H_earned_runs,H_bases_on_balls,H_strikeouts,H_plate_appearances,H_batting_average,...,A_Opp_grounded_balls,A_Opp_fly_balls,A_Opp_line_drives,A_Opp_unknown_bat_type,A_Opp_game_score,A_Opp_inherited_runners,A_Opp_inherited_score,A_Opp_win_probability_by_pitcher,A_Opp_base_out_runs_saved,home_win
0,NYY,34.462963,5.820988,9.216049,5.580247,5.632593,3.512346,8.870370,38.549383,0.262302,...,11.413580,16.395062,7.179012,0.000000,50.549383,1.385093,0.347826,0.068586,0.470370,1
1,TBR,34.740741,4.746914,8.808642,4.506173,4.573704,3.345679,9.216049,38.796296,0.249895,...,10.450617,13.179012,5.604938,0.018519,44.759259,1.679245,0.515723,-0.041290,-0.733333,0
2,TEX,34.197531,5.000000,8.481481,4.722222,4.666852,3.296296,9.740741,38.296296,0.242006,...,11.913580,13.555556,6.617284,0.000000,48.759259,1.487654,0.462963,-0.006420,-0.281481,0
3,MIA,34.024691,3.796296,8.185185,3.660494,3.545988,2.438272,9.067901,37.314815,0.234074,...,13.172840,14.685185,7.179012,0.000000,48.524691,1.347826,0.453416,0.017148,-0.015432,0
4,TOR,33.907407,4.481481,8.018519,4.302469,4.286975,3.141975,9.345679,37.598765,0.229025,...,11.869565,15.248447,6.645963,0.006211,54.776398,1.139241,0.316456,0.134677,1.446584,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2422,COL,34.938272,5.154321,9.271605,4.956790,4.874444,3.018519,9.277778,38.814815,0.260759,...,11.104938,14.345679,6.413580,0.000000,51.012346,1.530864,0.444444,-0.006605,0.037037,1
2423,NYM,34.716049,4.882716,8.919753,4.734568,4.590926,3.185185,8.543210,38.827160,0.252296,...,12.148148,13.956790,6.567901,0.006173,50.203704,1.416149,0.484472,-0.045481,-0.516667,1
2424,SEA,33.912500,4.650000,8.056250,4.475000,4.434688,3.606250,9.762500,38.168750,0.231038,...,11.356250,15.212500,6.450000,0.000000,49.300000,1.440252,0.427673,-0.045588,-0.432500,1
2425,SFG,34.438272,4.185185,8.222222,4.043210,3.882099,2.932099,8.858025,38.086420,0.233296,...,11.265432,13.018519,5.858025,0.000000,48.216049,1.481481,0.456790,-0.074901,-0.858642,0
2426,LAA,34.209877,4.746914,8.444444,4.530864,4.473765,3.617284,7.876543,38.586420,0.241494,...,10.450617,13.179012,5.604938,0.018519,44.759259,1.679245,0.515723,-0.041290,-0.733333,0

In [77]:
#Examine our new column
df_prep.home_win.value_counts(normalize=True)

1    0.529872
0    0.470128
Name: home_win, dtype: float64

In [80]:
df_prep

,H_name,H_at_bats,H_runs,H_hits,H_rbi,H_earned_runs,H_bases_on_balls,H_strikeouts,H_plate_appearances,H_batting_average,...,A_Opp_strikes_swinging,A_Opp_strikes_looking,A_Opp_grounded_balls,A_Opp_fly_balls,A_Opp_line_drives,A_Opp_unknown_bat_type,A_Opp_game_score,A_Opp_win_probability_by_pitcher,A_Opp_base_out_runs_saved,home_win
0,NYM,33.753086,4.172840,7.913580,4.006173,3.957531,3.493827,8.666667,38.129630,0.227963,...,16.104938,25.104938,12.265432,14.135802,6.796296,0.012346,50.376543,-0.040932,-0.425309,1
1,TEX,33.660494,4.549383,8.074074,4.296296,4.298580,3.425926,9.160494,38.043210,0.234926,...,18.549383,25.808642,10.456790,12.543210,5.716049,0.006173,48.870370,-0.019704,-0.457407,0
2,MIA,34.086957,3.658385,8.093168,3.440994,3.325901,2.826087,8.596273,37.782609,0.232317,...,15.185185,26.271605,12.117284,13.913580,6.697531,0.012346,51.425926,-0.004728,-0.308642,0
3,KCR,33.981481,3.938272,8.333333,3.740741,3.663580,2.635802,8.086420,37.425926,0.241000,...,15.055556,24.962963,11.197531,15.561728,6.635802,0.012346,54.080247,0.056796,0.490741,0
4,SDP,33.864198,3.808642,7.956790,3.598765,3.550988,2.907407,9.401235,37.401235,0.231272,...,16.623457,25.216049,11.290123,13.728395,6.413580,0.012346,50.697531,-0.045049,-0.317284,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2424,NYM,33.753086,4.172840,7.913580,4.006173,3.957531,3.493827,8.666667,38.129630,0.227963,...,15.161491,24.695652,11.341615,15.447205,6.708075,0.000000,53.944099,0.065081,0.559006,1
2425,SDP,33.864198,3.808642,7.956790,3.598765,3.550988,2.907407,9.401235,37.401235,0.231272,...,17.012346,26.265432,12.364198,13.030864,6.129630,0.000000,51.487654,0.015691,0.197531,1
2426,SEA,34.030864,4.179012,8.654321,3.975309,3.967778,2.654321,7.537037,37.574074,0.248759,...,13.351852,24.629630,12.401235,15.654321,7.148148,0.012346,52.074074,0.044549,0.182099,1
2427,CIN,34.148148,4.296296,8.666667,4.104938,4.181481,3.450617,8.493827,38.518519,0.248623,...,15.583851,23.987578,12.024845,14.366460,6.639752,0.000000,51.310559,0.006037,-0.067702,0
2428,KCR,33.981481,3.938272,8.333333,3.740741,3.663580,2.635802,8.086420,37.425926,0.241000,...,17.672840,25.604938,11.006173,14.055556,6.185185,0.006173,48.567901,0.005537,-0.463580,0


***

In [187]:
#df_16.drop(['index'],axis=1,inplace=True)

In [121]:
#df_16.set_index('date',inplace=True)

In [81]:
df_18.head()

,date,time,venue,attendance,duration,time_of_day,winner,home_name,home_abbr,away_name,...,home_grounded_balls,home_fly_balls,home_line_drives,home_unknown_bat_type,home_game_score,home_inherited_runners,home_inherited_score,home_win_probability_by_pitcher,home_base_out_runs_saved,winning_abbr
0,2018-03-29,1:16 p.m. Local,Citi Field,44189,3:01,Day,Home,New York Mets,NYM,St. Louis Cardinals,...,12,14,10,0,54,0,0,-0.056,-0.0,NYM
2,2018-03-29,2:40 p.m. Local,Globe Life Park in Arlington,47253,2:59,Day,Away,Texas Rangers,TEX,Houston Astros,...,5,17,6,0,50,1,0,-0.036,1.1,HOU
12,2018-03-29,12:43 p.m. Local,Marlins Park,32151,3:18,Day,Away,Miami Marlins,MIA,Chicago Cubs,...,14,13,6,0,28,2,2,-0.495,-3.9,CHC
8,2018-03-29,3:16 p.m. Local,Kauffman Stadium,36517,3:26,Day,Away,Kansas City Royals,KCR,Chicago White Sox,...,14,20,10,0,31,6,2,-0.606,-9.4,CHW
7,2018-03-29,1:12 p.m. Local,Petco Park,44649,3:36,Day,Away,San Diego Padres,SDP,Milwaukee Brewers,...,15,10,1,0,64,2,0,0.228,3.4,MIL

In [82]:
df_18.set_index('date',inplace=True)

### Create Season Dataframe

In [83]:
def create_season_df(df):
    
    #Reset the index
    df.reset_index(inplace=True)
  
    # create a DataFrame for the season we are looking for
    # season_df for whatever season you are looking for
    #season_df = df[df['date'] >= date]
    #reset index
    #season_df.reset_index(inplace = True)
    
    #Get home winners and Away winners in their own dataframe
    Home = df[(df['winner'] == 'Home')] 
    Away= df[(df['winner'] == 'Away')]
    
    #Rename columns in the home win from winner and loser to home and away
    Home=Home.rename(columns={'winning_abbr':'home_abbr','winning_name':'home_name','losing_name':'away_name',
                         'losing_abbr':'away_abbr'})
    
    #Rename columns in the away win from winner and loser to home and away
    Away= Away.rename(columns={'winning_abbr':'away_abbr','winning_name':'away_name','losing_name':'home_name',
                         'losing_abbr':'home_abbr'})
    
    #Concat these to make season_df now the same but with these new column names
    df= pd.concat([Home,Away])
    
    #Get Home and away alone once again
    Home = df[(df['winner'] == 'Home')] 
    Away= df[(df['winner'] == 'Away')]
    
    #Create a winning abbreviation column
    Home['winning_abbr']= Home['home_abbr']
    Away['winning_abbr']= Away['away_abbr']
    
    #Concat to update season_df
    df=pd.concat([Home,Away])
    
    #order it by date again
    df=df.sort_values('date')
    
    
    # create a list with the two teams, home team always first, the season, and the day number of the game
    matchups = list(zip(df.home_abbr, df.away_abbr, df.date, df.winning_abbr))
    
    season_games = [] 

    #loop through matchups and create single games for each matchup using that function, then append to season games
    for team in matchups:
        game = single_game(team[0], team[1],df)
        season_games.append(game)
    
    # from the season games list concatenate all the outputted DataFrames and insert the location
    # of the winner (home(1), away(0))
    df = pd.concat(season_games, axis = 0)
    #reset_index
    df.reset_index(inplace = True, drop = True)
    #Create new column where it will have a 1 if home team won and 0 if away team won
    df['home_win'] = np.where(df.home_abbr ==df.winning_abbr,
                  [1],
                  [0])
                       
    return df

In [78]:
season_2019=df_prep

In [79]:
season_2019.head(10)

,H_name,H_at_bats,H_runs,H_hits,H_rbi,H_earned_runs,H_bases_on_balls,H_strikeouts,H_plate_appearances,H_batting_average,...,A_Opp_grounded_balls,A_Opp_fly_balls,A_Opp_line_drives,A_Opp_unknown_bat_type,A_Opp_game_score,A_Opp_inherited_runners,A_Opp_inherited_score,A_Opp_win_probability_by_pitcher,A_Opp_base_out_runs_saved,home_win
0,NYY,34.462963,5.820988,9.216049,5.580247,5.632593,3.512346,8.870370,38.549383,0.262302,...,11.413580,16.395062,7.179012,0.000000,50.549383,1.385093,0.347826,0.068586,0.470370,1
1,TBR,34.740741,4.746914,8.808642,4.506173,4.573704,3.345679,9.216049,38.796296,0.249895,...,10.450617,13.179012,5.604938,0.018519,44.759259,1.679245,0.515723,-0.041290,-0.733333,0
2,TEX,34.197531,5.000000,8.481481,4.722222,4.666852,3.296296,9.740741,38.296296,0.242006,...,11.913580,13.555556,6.617284,0.000000,48.759259,1.487654,0.462963,-0.006420,-0.281481,0
3,MIA,34.024691,3.796296,8.185185,3.660494,3.545988,2.438272,9.067901,37.314815,0.234074,...,13.172840,14.685185,7.179012,0.000000,48.524691,1.347826,0.453416,0.017148,-0.015432,0
4,TOR,33.907407,4.481481,8.018519,4.302469,4.286975,3.141975,9.345679,37.598765,0.229025,...,11.869565,15.248447,6.645963,0.006211,54.776398,1.139241,0.316456,0.134677,1.446584,0
5,SEA,33.912500,4.650000,8.056250,4.475000,4.434688,3.606250,9.762500,38.168750,0.231038,...,11.000000,14.209877,6.265432,0.000000,47.216049,1.969136,0.623457,-0.009216,-0.516049,1
6,KCR,33.925926,4.265432,8.370370,4.043210,4.024012,2.814815,8.672840,37.530864,0.242494,...,11.434783,14.714286,6.850932,0.012422,52.267081,1.503185,0.490446,0.026969,0.414907,1
7,WSN,34.024691,5.388889,9.012346,5.086420,5.217346,3.604938,8.074074,38.685185,0.258451,...,11.364198,14.253086,6.351852,0.006173,50.135802,1.577640,0.534161,-0.024111,-0.288889,0
8,MIN,35.382716,5.796296,9.549383,5.592593,5.562531,3.240741,8.234568,39.456790,0.263704,...,10.000000,14.617284,6.345679,0.000000,50.265432,1.596273,0.534161,0.014932,0.192593,1
9,PHI,34.388889,4.777778,8.450617,4.580247,4.457963,3.469136,8.969136,38.648148,0.239568,...,12.148148,13.956790,6.567901,0.006173,50.203704,1.416149,0.484472,-0.045481,-0.516667,1

In [80]:
season_2019.to_csv('../data/Season_2019.csv')